#!/bin/sh

CONFIG=./tn-qc/bf8a1.conf
rm ./tn-qc/bf8a1_tmp.conf
cp "$CONFIG" ./tn-qc/bf8a1_tmp.conf

mac1=$(cat /sys/fsl_otp/HW_OCOTP_MAC1)
mac0=$(cat /sys/fsl_otp/HW_OCOTP_MAC0)

if [[ "$mac0" == "0x0" ]]; then
	if [[ "$mac1" == "0x0" ]]; then
                echo "burn_mode" > ./test_mode
		exit 0
        fi
else
	echo "normal_mode" > ./test_mode
fi

cd tn-qc
echo "" > all_pass 
echo "Failed" > results/Bluetooth/result.txt
echo "Failed" > results/CAN_bus/result.txt
echo "Failed" > results/CPU/result.txt
echo "Failed" > results/Ethernet/result.txt
echo "Failed" > results/GPIO/result.txt
echo "Failed" > results/I2C/result.txt
echo "Failed" > results/Memory/result.txt
echo "Failed" > results/mPCIE/result.txt
echo "Failed" > results/RTC/result.txt
echo "Failed" > results/SD/result.txt
echo "Failed" > results/SIM_card/result.txt
echo "Failed" > results/UART1/result.txt
echo "Failed" > results/USB/result.txt
echo "Failed" > results/Wifi/result.txt
echo "Failed" > results/AUDIO/result.txt
echo "Failed" > results/LVDS/result.txt
echo "Failed" > results/UART23/result.txt
echo "Failed" > results/SATA/result.txt
echo "Failed" > results/TOUCH/result.txt
echo "Failed" > results/UART4/result.txt
echo "Failed" > results/eFUSE/result.txt
echo "Failed" > results/eMMC/result.txt
echo "Failed" > results/PWM/result.txt
echo "Failed" > results/VGA/result.txt
rm results/MACs/*
./run_qc.sh &
./functions/getmac.sh &
cd -

while true; do
	cat $CONFIG | while read line; do
		cat tn-qc/results/$line/result.txt >> tn-qc/result_temp
	done
	cp tn-qc/result_temp tn-qc/result_final
	rm tn-qc/result_temp
	all_pass=$(cat ./tn-qc/result_final | grep "Failed")

	if [[ "$all_pass" == "" ]]; then                                 
        	echo "all_pass" > ./tn-qc/all_pass
	else                                                                   
        	echo "" > ./tn-qc/all_pass
	fi                                

	sleep 1
done
