#!/bin/sh

CONFIG=./tn-qc/st7b2.conf

cd tn-qc
./run_qc.sh &
cd -

while true; do
	
	cat $CONFIG | while read line; do
		cat tn-qc/results/$line/result.txt >> tn-qc/result_temp
	done
	cp tn-qc/result_temp tn-qc/result_final
	rm tn-qc/result_temp
done
