#!/bin/sh

MAC=$(cat /root/qc-web/id_mac.csv | awk -F, '{print $2}')

mac1=$(echo "$MAC" | awk -F: '{print $1}')
mac2=$(echo "$MAC" | awk -F: '{print $2}')
mac3=$(echo "$MAC" | awk -F: '{print $3}')
mac4=$(echo "$MAC" | awk -F: '{print $4}')
mac5=$(echo "$MAC" | awk -F: '{print $5}')
mac6=$(echo "$MAC" | awk -F: '{print $6}')

echo "0x$mac1$mac2" > /sys/fsl_otp/HW_OCOTP_MAC1
echo "0x$mac3$mac4$mac5$mac6" > /sys/fsl_otp/HW_OCOTP_MAC0

sync

poweroff
